using System.Data;
using InvoicerBackend;
using Microsoft.EntityFrameworkCore;
using RV.InvNew.Common;

namespace InvoicerBackend
{
    public static class CycleCountEndpoints
    {
        public static WebApplication AddCycleCountEndpoints(this WebApplication app)
        {
            // Add a new cycle count entry
            app.AddAsyncEndpointWithBearerAuth<CycleCount>(
                "AddCycleCount",
                async (AS, LoginInfo) =>
                {
                    var Entry = (CycleCount)AS;
                    System.Console.WriteLine(
                        $"AddCycleCount: {LoginInfo.UserId}, {LoginInfo.Principal}"
                    );
                    Entry.PrincipalId = (long)LoginInfo.UserId;
                    Entry.PrincipalName = LoginInfo.Principal;
                    Entry.CountDate = DateTime.UtcNow;
                    // SeqNo will be auto-generated by PostgreSQL's BIGSERIAL

                    using (var ctx = new NewinvContext())
                    {
                        var tx = await ctx.Database.BeginTransactionAsync(
                            IsolationLevel.Serializable
                        );

                        // Get the current recorded quantity from inventory (summing all batches)
                        var inventoryQuantity = await ctx.Inventories
                            .Where(ii => ii.Itemcode == Entry.Itemcode)
                            .SumAsync(ii => ii.Units);

                        Entry.RecordedQty = inventoryQuantity;

                        ctx.CycleCounts.Add(Entry);
                        await ctx.SaveChangesAsync();
                        await tx.CommitAsync();
                    }
                    return 0;
                },
                "Refresh"
            );

            // Get the latest cycle count for a specific item
            app.AddEndpointWithBearerAuth<long>(
                "GetLatestCycleCount",
                (AS, LoginInfo) =>
                {
                    var itemcode = (long)AS;
                    CycleCount cycleCount;

                    using (var ctx = new NewinvContext())
                    {
                        // Using the view to get the latest cycle count
                        cycleCount = ctx.CycleCounts
                            .FromSqlRaw("SELECT * FROM latest_cycle_count WHERE itemcode = {0}", itemcode)
                            .AsEnumerable()
                            .FirstOrDefault();
                    }

                    return cycleCount;
                },
                "Refresh"
            );

            // Get cycle count history for a specific item
            app.AddEndpointWithBearerAuth<long>(
                "GetCycleCountHistory",
                (AS, LoginInfo) =>
                {
                    var itemcode = (long)AS;
                    List<CycleCount> cycleCountHistory;

                    using (var ctx = new NewinvContext())
                    {
                        cycleCountHistory = ctx.CycleCounts
                            .Where(cc => cc.Itemcode == itemcode)
                            .OrderByDescending(cc => cc.SeqNo)
                            .ToList();
                    }

                    return cycleCountHistory;
                },
                "Refresh"
            );

            // Search cycle counts (omnibox style)
            app.AddEndpointWithBearerAuth<string>(
                "SearchCycleCounts",
                (AS, LoginInfo) =>
                {
                    var searchTerm = (string)AS;
                    List<CycleCount> searchResults;

                    using (var ctx = new NewinvContext())
                    {
                        // Search across multiple fields
                        searchResults = ctx.CycleCounts
                            .Where(cc =>
                                cc.Itemcode.ToString().Contains(searchTerm) ||
                                (cc.Location != null && cc.Location.Contains(searchTerm)) ||
                                (cc.Notes != null && cc.Notes.Contains(searchTerm)) ||
                                (cc.PrincipalName != null && cc.PrincipalName.Contains(searchTerm)))
                            .OrderByDescending(cc => cc.SeqNo)
                            .ToList();
                    }

                    return searchResults;
                },
                "Refresh"
            );

            // Get all cycle counts
            app.AddEndpointWithBearerAuth<string>(
                "GetAllCycleCounts",
                (AS, LoginInfo) =>
                {
                    List<CycleCount> allCycleCounts;

                    using (var ctx = new NewinvContext())
                    {
                        allCycleCounts = ctx.CycleCounts
                            .OrderByDescending(cc => cc.SeqNo)
                            .ToList();
                    }

                    return allCycleCounts;
                },
                "Refresh"
            );

            // Get cycle counts within a time period
            app.AddEndpointWithBearerAuth<TimePeriod>(
                "GetCycleCountsWithinTimePeriod",
                (AS, LoginInfo) =>
                {
                    var TP = (TimePeriod)AS;
                    List<CycleCount> cycleCounts;

                    using (var ctx = new NewinvContext())
                    {
                        cycleCounts = ctx.CycleCounts
                            .Where(cc =>
                                cc.CountDate >= TP.From.Value.ToUniversalTime() &&
                                cc.CountDate <= TP.To.Value.ToUniversalTime())
                            .OrderByDescending(cc => cc.SeqNo)
                            .ToList();
                    }

                    System.Console.WriteLine($"From, To: {TP.From}, {TP.To}");
                    return cycleCounts;
                },
                "Refresh"
            );

            // Get cycle counts with discrepancies
            app.AddEndpointWithBearerAuth<string>(
                "GetCycleCountsWithDiscrepancies",
                (AS, LoginInfo) =>
                {
                    List<CycleCount> discrepancyCycleCounts;

                    using (var ctx = new NewinvContext())
                    {
                        discrepancyCycleCounts = ctx.CycleCounts
                            .Where(cc => cc.RecordedQty != cc.ActualQty)
                            .OrderByDescending(cc => cc.SeqNo)
                            .ToList();
                    }

                    return discrepancyCycleCounts;
                },
                "Refresh"
            );

            return app;
        }
    }
}