[si]
"Editor" = "📝 සංස්කාරක"
"BatchEditor" = "📋 බැච් සංස්කාරක"
"Adjustments" = "🔧 වෙනස්කම්"
"Items" = "📦 අයිතම"
"StockOverview" = "📊 කොටස් සමාලෝචනය"
"Locations" = "📍 ස්ථාන"
"Transfers" = "🔄 මාරු"
"Reports" = "📈 වාර්තා"
"Alerts" = "⛑ අනතුරු ඇඟවීම්"
"Search" = "🔍 සෙවුම්"
"MaterialMaster" = "🗃 ද්‍රව්‍ය පාලක"
"GoodsReceipt" = "📥 භාණ්ඩ ලැබීම"
"GoodsIssued" = "📤 භාණ්ඩ නිකුත්කිරීම"
"CycleCount" = "🧮 චක්‍ර ගණන"
"Warehouse" = "🏭 ගබඩා"
"SerialControl" = "🔢 අනුක්‍රමික පාලනය"
"Replenishment" = "🔄 නැවත පිරවීම්"
"BarcodePrint" = "🖨️ බාකෝඩ් මුද්‍රණය"
"Inventory" = "📦 ගබඩා"
"Accounts" = "💰 ගිණුම්"
"HR" = "👥 සේවක කළමනාකරණය"
"CRM" = "🤝 ගනුදෙනු කළමනාකරණය"
"Settings" = "⚙️ සැකසුම්"
"Connection" = "⚙️ සම්බන්ධතාවය"
"About" = "🎫 පිළිබඳ විස්තර"

[ta]
"Editor" = "📝 தொகுப்பாளர்"
"BatchEditor" = "📋 தொகுதி திருத்தி"
"Adjustments" = "🔧 சரிசெய்தல்கள்"
"Items" = "📦 பொருட்கள்"
"StockOverview" = "📊 களஞ்சிய கண்ணோட்டம்"
"Locations" = "📍 இருப்பிடங்கள்"
"Transfers" = "🔄 மாற்றங்கள்"
"Reports" = "📈 அறிக்கைகள்"
"Alerts" = "⛑ எச்சரிக்கை"
"Search" = "🔍 தேடல்"
"MaterialMaster" = "🗃 பொருள் மேலாளர்"
"GoodsReceipt" = "📥 பொருட்கள் பெறுதல்"
"GoodsIssued" = "📤 பொருட்கள் வெளியீடு"
"CycleCount" = "🧮 சுழற்சி எண்ணிக்கை"
"Warehouse" = "🏭 களஞ்சியம்"
"SerialControl" = "🔢 தொடர் கட்டுப்பாடு"
"Replenishment" = "🔄 நிரப்புதல்"
"BarcodePrint" = "🖨️ பார்கோடு அச்சிடுதல்"
"Inventory" = "📦 களஞ்சியம்"
"Accounts" = "💰 கணக்குகள்"
"HR" = "👥 மனிதவள மேலாண்மை"
"CRM" = "🤝 வாடிக்கையாளர் மேலாண்மை"
"Settings" = "⚙️ அமைப்புகள்"
"Connection" = "⚙️ தற்போதைய இணைப்பு"
"About" = "🎫 பற்றி"

[hi]
"Editor" = "📝 संपादक"
"BatchEditor" = "📋 बैच संपादक"
"Adjustments" = "🔧 समायोजन"
"Items" = "📦 वस्तुएँ"
"StockOverview" = "📊 स्टॉक अवलोकन"
"Locations" = "📍 स्थान"
"Transfers" = "🔄 स्थानांतरण"
"Reports" = "📈 रिपोर्ट"
"Alerts" = "⛑ चेतावनी"
"Search" = "🔍 खोज"
"MaterialMaster" = "🗃 सामग्री प्रबंधक"
"GoodsReceipt" = "📥 माल प्राप्ति"
"GoodsIssued" = "📤 माल जारी"
"CycleCount" = "🧮 चक्र गिनती"
"Warehouse" = "🏭 गोदाम"
"SerialControl" = "🔢 क्रम नियंत्रण"
"Replenishment" = "🔄 पुनःपूर्ति"
"BarcodePrint" = "🖨️ बारकोड प्रिंट"
"Inventory" = "📦 इन्वेंटरी"
"Accounts" = "💰 खाते"
"HR" = "👥 मानव संसाधन"
"CRM" = "🤝 ग्राहक प्रबंधन"
"Settings" = "⚙️ सेटिंग्स"
"Connection" = "⚙️ वर्तमान कनेक्शन"
"About" = "🎫 बारे में"

[fr]
"Editor" = "📝 Éditeur"
"BatchEditor" = "📋 Éditeur par lots"
"Adjustments" = "🔧 Ajustements"
"Items" = "📦 Articles"
"StockOverview" = "📊 Aperçu du stock"
"Locations" = "📍 Emplacements"
"Transfers" = "🔄 Transferts"
"Reports" = "📈 Rapports"
"Alerts" = "⛑ Alertes"
"Search" = "🔍 Recherche"
"MaterialMaster" = "🗃 Gestion des matériaux"
"GoodsReceipt" = "📥 Réception des marchandises"
"GoodsIssued" = "📤 Sortie des marchandises"
"CycleCount" = "🧮 Comptage cyclique"
"Warehouse" = "🏭 Entrepôt"
"SerialControl" = "🔢 Contrôle de série"
"Replenishment" = "🔄 Réapprovisionnement"
"BarcodePrint" = "🖨️ Impression de codes-barres"
"Inventory" = "📦 Inventaire"
"Accounts" = "💰 Comptes"
"HR" = "👥 Ressources Humaines"
"CRM" = "🤝 Gestion de la relation client"
"Settings" = "⚙️ Paramètres"
"Connection" = "⚙️ Connexion actuelle"
"About" = "🎫 À propos"