[en]
Active = "Active"
ActiveWeb = "Active on Web"
CategoriesBitmask = "Categories Bitmask"
CreatedOn = "Created On"
DefaultVatCategory = "Default VAT Category"
Description = "Description"
DescriptionPos = "POS Description"
DescriptionsOtherLanguages = "Descriptions in Other Languages"
DescriptionWeb = "Web Description"
EnforceAboveCost = "Enforce Above Cost"
ExpiryTrackingEnabled = "Expiry Tracking Enabled"
Itemcode = "Item Code"
PermissionsCategory = "Permissions Category"
PriceManual = "Manual Price"
VatCategoryAdjustable = "VAT Category Adjustable"
VatDependsOnUser = "VAT Depends on User"
New = "New"
Save = "Save"
View = "View"
Cancel = "Cancel"

[si]
"Editor" = "📝 සංස්කාරක"
"BatchEditor" = "📋 බැච් සංස්කාරක"
"Adjustments" = "🔧 වෙනස්කම්"
"Items" = "📦 අයිතම"
"StockOverview" = "📊 කොටස් සමාලෝචනය"
"Locations" = "📍 ස්ථාන"
"Transfers" = "🔄 මාරු"
"Reports" = "📈 වාර්තා"
"Alerts" = "⛑ අනතුරු ඇඟවීම්"
"Search" = "🔍 සෙවුම්"
"MaterialMaster" = "🗃 ද්‍රව්‍ය පාලක"
"GoodsReceipt" = "📥 භාණ්ඩ ලැබීම"
"GoodsIssued" = "📤 භාණ්ඩ නිකුත්කිරීම"
"CycleCount" = "🧮 චක්‍ර ගණන"
"Warehouse" = "🏭 ගබඩා"
"SerialControl" = "🔢 අනුක්‍රමික පාලනය"
"Replenishment" = "🔄 නැවත පිරවීම්"
"BarcodePrint" = "🖨️ බාකෝඩ් මුද්‍රණය"
"Inventory" = "📦 ගබඩා"
"Accounts" = "💰 ගිණුම්"
"HR" = "👥 සේවක කළමනාකරණය"
"CRM" = "🤝 ගනුදෙනු කළමනාකරණය"
"Settings" = "⚙️ සැකසුම්"
"Connection" = "⚙️ සම්බන්ධතාවය"
"About" = "🎫 පිළිබඳ විස්තර"
ReportSelected         = "වාර්තාව තෝරා ඇත"
SearchFor              = "සෙවීමට: "
Results                = "ප්‍රතිඵල: "
CaseInsensitiveF1      = "අකුරු සංවේදනය නොවන [F1]"
CaseSensitiveF2        = "අකුරු සංවේදනය වන [F2]"
ContainsF3             = "අඩංගු [F3]"
StartsWithF4           = "ආරම්භ [F4]"
AnythingAnywhereBRK    = "ඕනෑම දෙයක් ඕනෑම තැන [BRK]"
NormalizeSpellingEND   = "වචන නිවැරදි කිරීම [END]"
SearchIn               = "සොයන්න: "
CaseSensitivitySetting = "අකුරු සංවේදන සැකසුම්"
SearchPosition         = "සෙවුම් ස්ථානය"
Advanced               = "උසස්..."
ExportResults          = "ප්‍රතිඵල ගොනුවට අපනයනය කරන්න..."
ExportEverything       = "සියල්ල ගොනුවට අපනයනය කරන්න..."
ExportDisplayed        = "දර්ශනය කරන ප්‍රතිඵල ගොනුවට අපනයනය කරන්න..."
ExportOptions          = "ගොනුවට අපනයනය විකල්ප"
PrintingOptions        = "මුද්‍රණ විකල්ප"
PrintDisplayed         = "දර්ශනය කරන ප්‍රතිඵල මුද්‍රණය..."
Itemcode = "භාණ්ඩ හැඳුනුම් කේතය"
Name     = "භාණ්ඩ නම"
Active = "සක්‍රීය"
ActiveWeb = "වෙබ් සක්‍රීය"
CategoriesBitmask = "ප්‍රවර්ග බිට්මාස්ක්"
CreatedOn = "නිර්මාණය කරන ලද දිනය"
DefaultVatCategory = "පෙරනිමි VAT ප්‍රවර්ගය"
Description = "විස්තරය"
DescriptionPos = "POS විස්තරය"
DescriptionsOtherLanguages = "වෙනත් භාෂා වල විස්තර"
DescriptionWeb = "වෙබ් විස්තරය"
EnforceAboveCost = "වියදම ඉහළ ක්‍රියාත්මක කිරීම"
ExpiryTrackingEnabled = "කල් ඉකුත් වීම සක්‍රීයයි"
#Itemcode = "අයිතම කේතය"
PermissionsCategory = "අවසර ප්‍රවර්ගය"
PriceManual = "මැනුවල් මිල"
VatCategoryAdjustable = "VAT ප්‍රවර්ගය වෙනස් කළ හැකි"
VatDependsOnUser = "VAT පරිශීලකයා මත රඳා පවතියි"
New = "නව"
Save = "සුරකින්න"
View = "බලන්න"
Cancel = "අවලංගු කරන්න"


[ta]
"Editor" = "📝 தொகுப்பாளர்"
"BatchEditor" = "📋 தொகுதி திருத்தி"
"Adjustments" = "🔧 சரிசெய்தல்கள்"
"Items" = "📦 பொருட்கள்"
"StockOverview" = "📊 களஞ்சிய கண்ணோட்டம்"
"Locations" = "📍 இருப்பிடங்கள்"
"Transfers" = "🔄 மாற்றங்கள்"
"Reports" = "📈 அறிக்கைகள்"
"Alerts" = "⛑ எச்சரிக்கை"
"Search" = "🔍 தேடல்"
"MaterialMaster" = "🗃 பொருள் மேலாளர்"
"GoodsReceipt" = "📥 பொருட்கள் பெறுதல்"
"GoodsIssued" = "📤 பொருட்கள் வெளியீடு"
"CycleCount" = "🧮 சுழற்சி எண்ணிக்கை"
"Warehouse" = "🏭 களஞ்சியம்"
"SerialControl" = "🔢 தொடர் கட்டுப்பாடு"
"Replenishment" = "🔄 நிரப்புதல்"
"BarcodePrint" = "🖨️ பார்கோடு அச்சிடுதல்"
"Inventory" = "📦 களஞ்சியம்"
"Accounts" = "💰 கணக்குகள்"
"HR" = "👥 மனிதவள மேலாண்மை"
"CRM" = "🤝 வாடிக்கையாளர் மேலாண்மை"
"Settings" = "⚙️ அமைப்புகள்"
"Connection" = "⚙️ தற்போதைய இணைப்பு"
"About" = "🎫 பற்றி"
ReportSelected         = "அறிக்கை தெரிவு செய்யப்பட்டு உள்ளது"
SearchFor              = "தேடவும்: "
Results                = "முடிவுகள்: "
CaseInsensitiveF1      = "எழுத்துப் பொருத்தமற்றது [F1]"
CaseSensitiveF2        = "எழுத்துப் பொருத்தமானது [F2]"
ContainsF3             = "உள்ளடக்கம் [F3]"
StartsWithF4           = "ஆரம்பம் [F4]"
AnythingAnywhereBRK    = "எதையும் எங்கும் [BRK]"
NormalizeSpellingEND   = "எழுத்து ஒழுங்குபடுத்தல் [END]"
SearchIn               = "தேடல் இடம்: "
CaseSensitivitySetting = "எழுத்து உணர்திறன் அமைப்பு"
SearchPosition         = "தேடல் நிலை"
Advanced               = "மேம்பட்டது..."
ExportResults          = "முடிவுகளை கோப்பாக ஏற்றுமதி செய்க..."
ExportEverything       = "எல்லாவற்றையும் கோப்பாக ஏற்றுமதி செய்க..."
ExportDisplayed        = "காண்பிக்கப்படும் முடிவுகளை கோப்பாக ஏற்றுமதி செய்க..."
ExportOptions          = "கோப்பு ஏற்றுமதி விருப்பங்கள்"
PrintingOptions        = "அச்சிடும் விருப்பங்கள்"
PrintDisplayed         = "காண்பிக்கப்படும் முடிவுகளை அச்சிடுக..."
Itemcode = "பொருள் குறியீடு"
Name     = "பெயர்"
Active = "செயலில்"
ActiveWeb = "இணையத்தில் செயலில்"
CategoriesBitmask = "வகை பிட்மாஸ்க்"
CreatedOn = "உருவாக்கப்பட்ட தேதி"
DefaultVatCategory = "இயல்புநிலை வரி வகை"
Description = "விவரம்"
DescriptionPos = "POS விவரம்"
DescriptionsOtherLanguages = "மற்ற மொழிகளில் விவரம்"
DescriptionWeb = "இணைய விவரம்"
EnforceAboveCost = "செலவிற்கு மேல் கட்டாயப்படுத்தல்"
ExpiryTrackingEnabled = "காலாவதி கண்காணிப்பு இயக்கு"
#Itemcode = "உருப்படி குறியீடு"
PermissionsCategory = "அனுமதி வகை"
PriceManual = "கைமுறை விலை"
VatCategoryAdjustable = "வரி வகை மாற்றக்கூடியது"
VatDependsOnUser = "வரி பயனரை சார்ந்தது"
New = "புதிய"
Save = "சேமிக்கவும்"
View = "காண்க"
Cancel = "ரத்து செய்யவும்"


[hi]
"Editor" = "📝 संपादक"
"BatchEditor" = "📋 बैच संपादक"
"Adjustments" = "🔧 समायोजन"
"Items" = "📦 वस्तुएँ"
"StockOverview" = "📊 स्टॉक अवलोकन"
"Locations" = "📍 स्थान"
"Transfers" = "🔄 स्थानांतरण"
"Reports" = "📈 रिपोर्ट"
"Alerts" = "⛑ चेतावनी"
"Search" = "🔍 खोज"
"MaterialMaster" = "🗃 सामग्री प्रबंधक"
"GoodsReceipt" = "📥 माल प्राप्ति"
"GoodsIssued" = "📤 माल जारी"
"CycleCount" = "🧮 चक्र गिनती"
"Warehouse" = "🏭 गोदाम"
"SerialControl" = "🔢 क्रम नियंत्रण"
"Replenishment" = "🔄 पुनःपूर्ति"
"BarcodePrint" = "🖨️ बारकोड प्रिंट"
"Inventory" = "📦 इन्वेंटरी"
"Accounts" = "💰 खाते"
"HR" = "👥 मानव संसाधन"
"CRM" = "🤝 ग्राहक प्रबंधन"
"Settings" = "⚙️ सेटिंग्स"
"Connection" = "⚙️ वर्तमान कनेक्शन"
"About" = "🎫 बारे में"
ReportSelected         = "रिपोर्ट चुनी गई"
SearchFor              = "खोजें: "
Results                = "परिणाम: "
CaseInsensitiveF1      = "केस-संवेदनहीन [F1]"
CaseSensitiveF2        = "केस-संवेदनशील [F2]"
ContainsF3             = "शामिल [F3]"
StartsWithF4           = "से शुरू [F4]"
AnythingAnywhereBRK    = "कुछ भी कहीं भी [BRK]"
NormalizeSpellingEND   = "वर्तनी सामान्य करें [END]"
SearchIn               = "में खोजें: "
CaseSensitivitySetting = "अक्षर संवेदनशीलता सेटिंग"
SearchPosition         = "खोज स्थिति"
Advanced               = "उन्नत..."
ExportResults          = "परिणामों को फ़ाइल में निर्यात करें..."
ExportEverything       = "सभी को फ़ाइल में निर्यात करें..."
ExportDisplayed        = "दिखाए गए परिणामों को फ़ाइल में निर्यात करें..."
ExportOptions          = "फ़ाइल निर्यात विकल्प"
PrintingOptions        = "प्रिंट विकल्प"
PrintDisplayed         = "दिखाए गए परिणाम प्रिंट करें..."
Itemcode = "आइटम कोड"
Name     = "आइटम नाम"
Active = "सक्रिय"
ActiveWeb = "वेब पर सक्रिय"
CategoriesBitmask = "श्रेणी बिटमास्क"
CreatedOn = "निर्मित तिथि"
DefaultVatCategory = "डिफ़ॉल्ट वैट श्रेणी"
Description = "विवरण"
DescriptionPos = "POS विवरण"
DescriptionsOtherLanguages = "अन्य भाषाओं में विवरण"
DescriptionWeb = "वेब विवरण"
EnforceAboveCost = "लागत से ऊपर लागू करें"
ExpiryTrackingEnabled = "समाप्ति ट्रैकिंग सक्षम"
#Itemcode = "आइटम कोड"
PermissionsCategory = "अनुमति श्रेणी"
PriceManual = "मैनुअल मूल्य"
VatCategoryAdjustable = "वैट श्रेणी समायोज्य"
VatDependsOnUser = "वैट उपयोगकर्ता पर निर्भर"
New = "नया"
Save = "सहेजें"
View = "देखें"
Cancel = "रद्द करें"

[fr]
"Editor" = "📝 Éditeur"
"BatchEditor" = "📋 Éditeur par lots"
"Adjustments" = "🔧 Ajustements"
"Items" = "📦 Articles"
"StockOverview" = "📊 Aperçu du stock"
"Locations" = "📍 Emplacements"
"Transfers" = "🔄 Transferts"
"Reports" = "📈 Rapports"
"Alerts" = "⛑ Alertes"
"Search" = "🔍 Recherche"
"MaterialMaster" = "🗃 Gestion des matériaux"
"GoodsReceipt" = "📥 Réception des marchandises"
"GoodsIssued" = "📤 Sortie des marchandises"
"CycleCount" = "🧮 Comptage cyclique"
"Warehouse" = "🏭 Entrepôt"
"SerialControl" = "🔢 Contrôle de série"
"Replenishment" = "🔄 Réapprovisionnement"
"BarcodePrint" = "🖨️ Impression de codes-barres"
"Inventory" = "📦 Inventaire"
"Accounts" = "💰 Comptes"
"HR" = "👥 Ressources Humaines"
"CRM" = "🤝 Gestion de la relation client"
"Settings" = "⚙️ Paramètres"
"Connection" = "⚙️ Connexion actuelle"
"About" = "🎫 À propos"
ReportSelected         = "Rapport sélectionné"
SearchFor              = "Rechercher : "
Results                = "Résultats : "
CaseInsensitiveF1      = "Insensible à la casse [F1]"
CaseSensitiveF2        = "Sensible à la casse [F2]"
ContainsF3             = "Contient [F3]"
StartsWithF4           = "Commence par [F4]"
AnythingAnywhereBRK    = "N'importe quoi n'importe où [BRK]"
NormalizeSpellingEND   = "Normaliser l'orthographe [END]"
SearchIn               = "Rechercher dans : "
CaseSensitivitySetting = "Sensibilité à la casse"
SearchPosition         = "Position de recherche"
Advanced               = "Avancé..."
ExportResults          = "Exporter les résultats vers un fichier..."
ExportEverything       = "Exporter tout vers un fichier..."
ExportDisplayed        = "Exporter les affichages vers un fichier..."
ExportOptions          = "Options d'exportation de fichier"
PrintingOptions        = "Options d'impression"
PrintDisplayed         = "Imprimer les affichages..."
Itemcode = "Code article"
Name     = "Nom de l'article"
Active = "Actif"
ActiveWeb = "Actif sur le Web"
CategoriesBitmask = "Masque de catégories"
CreatedOn = "Créé le"
DefaultVatCategory = "Catégorie de TVA par défaut"
Description = "Description"
DescriptionPos = "Description POS"
DescriptionsOtherLanguages = "Descriptions dans d’autres langues"
DescriptionWeb = "Description Web"
EnforceAboveCost = "Appliquer au‐dessus du coût"
ExpiryTrackingEnabled = "Suivi de péremption activé"
#Itemcode = "Code d’article"
PermissionsCategory = "Catégorie de permissions"
PriceManual = "Prix manuel"
VatCategoryAdjustable = "Catégorie de TVA ajustable"
VatDependsOnUser = "TVA dépend de l’utilisateur"
New = "Nouveau"
Save = "Enregistrer"
View = "Voir"
Cancel = "Annuler"

[ja]
Editor = "📝 編集者"
BatchEditor = "📋 一括編集"
Adjustments = "🔧 調整"
Items = "📦 品目"
StockOverview = "📊 在庫概要"
Locations = "📍 場所"
Transfers = "🔄 転送"
Reports = "📈 レポート"
Alerts = "⛑ 警告"
Search = "🔍 検索"
MaterialMaster = "🗃 資材管理"
GoodsReceipt = "📥 入荷"
GoodsIssued = "📤 出庫"
CycleCount = "🧮 サイクルカウント"
Warehouse = "🏭 倉庫"
SerialControl = "🔢 シリアル管理"
Replenishment = "🔄 補充"
BarcodePrint = "🖨️ バーコード印刷"
Inventory = "📦 在庫"
Accounts = "💰 会計"
HR = "👥 人事"
CRM = "🤝 顧客管理"
Settings = "⚙️ 設定"
Connection = "⚙️ 現在の接続"
About = "🎫 このソフトについて"
ReportSelected = "選択されたレポート"
SearchFor = "検索: "
Results = "結果: "
CaseInsensitiveF1 = "大文字小文字を区別しない [F1]"
CaseSensitiveF2 = "大文字小文字を区別する [F2]"
ContainsF3 = "含む [F3]"
StartsWithF4 = "で始まる [F4]"
AnythingAnywhereBRK = "どこでも何でも [BRK]"
NormalizeSpellingEND = "スペルの正規化 [END]"
SearchIn = "検索対象: "
CaseSensitivitySetting = "大文字小文字の設定"
SearchPosition = "検索位置"
Advanced = "詳細設定..."
ExportResults = "結果をファイルにエクスポート..."
ExportEverything = "すべてをファイルにエクスポート..."
ExportDisplayed = "表示中の項目をファイルにエクスポート..."
ExportOptions = "ファイル出力のオプション"
PrintingOptions = "印刷オプション"
PrintDisplayed = "表示内容を印刷..."
Itemcode = "商品コード"
Name = "商品名"
Active = "有効"
ActiveWeb = "ウェブ上で有効"
CategoriesBitmask = "カテゴリー ビットマスク"
CreatedOn = "作成日"
DefaultVatCategory = "標準VATカテゴリー"
Description = "説明"
DescriptionPos = "POS説明"
DescriptionsOtherLanguages = "他言語での説明"
DescriptionWeb = "Web説明"
EnforceAboveCost = "原価以上を強制"
ExpiryTrackingEnabled = "有効期限追跡有効"
#Itemcode = "商品コード (注：旧表記)"
PermissionsCategory = "権限カテゴリ"
PriceManual = "手動価格"
VatCategoryAdjustable = "VATカテゴリー調整可能"
VatDependsOnUser = "VATはユーザーに依存"
New = "新規"
Save = "保存"
View = "表示"
Cancel = "キャンセル"

[zh]
Editor = "📝 编辑"
BatchEditor = "📋 批量编辑"
Adjustments = "🔧 调整"
Items = "📦 物品"
StockOverview = "📊 库存概览"
Locations = "📍 位置"
Transfers = "🔄 调拨"
Reports = "📈 报告"
Alerts = "⛑ 警告"
Search = "🔍 搜索"
MaterialMaster = "🗃 物料管理"
GoodsReceipt = "📥 收货"
GoodsIssued = "📤 出库"
CycleCount = "🧮 循环盘点"
Warehouse = "🏭 仓库"
SerialControl = "🔢 序列号控制"
Replenishment = "🔄 补货"
BarcodePrint = "🖨️ 条码打印"
Inventory = "📦 库存"
Accounts = "💰 账户"
HR = "👥 人力资源"
CRM = "🤝 客户关系管理"
Settings = "⚙️ 设置"
Connection = "⚙️ 当前连接"
About = "🎫 关于"
ReportSelected = "所选报告"
SearchFor = "搜索: "
Results = "结果: "
CaseInsensitiveF1 = "不区分大小写 [F1]"
CaseSensitiveF2 = "区分大小写 [F2]"
ContainsF3 = "包含 [F3]"
StartsWithF4 = "以...开始 [F4]"
AnythingAnywhereBRK = "任何地方任何内容 [BRK]"
NormalizeSpellingEND = "规范拼写 [END]"
SearchIn = "在...中搜索: "
CaseSensitivitySetting = "大小写敏感设置"
SearchPosition = "搜索位置"
Advanced = "高级..."
ExportResults = "将结果导出到文件..."
ExportEverything = "将所有内容导出到文件..."
ExportDisplayed = "将显示内容导出到文件..."
ExportOptions = "文件导出选项"
PrintingOptions = "打印选项"
PrintDisplayed = "打印显示内容..."
Itemcode = "商品编码"
Name = "商品名称"
Active = "激活"
ActiveWeb = "在网页上激活"
CategoriesBitmask = "类别位掩码"
CreatedOn = "创建于"
DefaultVatCategory = "默认增值税类别"
Description = "描述"
DescriptionPos = "POS描述"
DescriptionsOtherLanguages = "其他语言的描述"
DescriptionWeb = "网页描述"
EnforceAboveCost = "强制高于成本"
ExpiryTrackingEnabled = "启用到期跟踪"
#Itemcode = "商品编码 (注：旧表记)"
PermissionsCategory = "权限类别"
PriceManual = "手动定价"
VatCategoryAdjustable = "可调整增值税类别"
VatDependsOnUser = "增值税取决于用户"
New = "新建"
Save = "保存"
View = "查看"
Cancel = "取消"

[es]
Editor = "📝 Editor"
BatchEditor = "📋 Editor por lotes"
Adjustments = "🔧 Ajustes"
Items = "📦 Artículos"
StockOverview = "📊 Resumen de stock"
Locations = "📍 Ubicaciones"
Transfers = "🔄 Transferencias"
Reports = "📈 Informes"
Alerts = "⛑ Alertas"
Search = "🔍 Buscar"
MaterialMaster = "🗃 Gestión de materiales"
GoodsReceipt = "📥 Recepción de mercancías"
GoodsIssued = "📤 Salida de mercancías"
CycleCount = "🧮 Conteo cíclico"
Warehouse = "🏭 Almacén"
SerialControl = "🔢 Control de serie"
Replenishment = "🔄 Reabastecimiento"
BarcodePrint = "🖨️ Impresión de códigos de barras"
Inventory = "📦 Inventario"
Accounts = "💰 Cuentas"
HR = "👥 Recursos Humanos"
CRM = "🤝 Gestión de relaciones con clientes"
Settings = "⚙️ Configuración"
Connection = "⚙️ Conexión actual"
About = "🎫 Acerca de"
ReportSelected = "Informe seleccionado"
SearchFor = "Buscar: "
Results = "Resultados: "
CaseInsensitiveF1 = "Sin distinguir mayúsculas/minúsculas [F1]"
CaseSensitiveF2 = "Con distinción de mayúsculas/minúsculas [F2]"
ContainsF3 = "Contiene [F3]"
StartsWithF4 = "Empieza con [F4]"
AnythingAnywhereBRK = "Cualquier cosa en cualquier lugar [BRK]"
NormalizeSpellingEND = "Normalizar ortografía [END]"
SearchIn = "Buscar en: "
CaseSensitivitySetting = "Configuración de sensibilidad a mayúsculas/minúsculas"
SearchPosition = "Posición de búsqueda"
Advanced = "Avanzado..."
ExportResults = "Exportar resultados a un archivo..."
ExportEverything = "Exportar todo a un archivo..."
ExportDisplayed = "Exportar elementos mostrados a un archivo..."
ExportOptions = "Opciones de exportación de archivo"
PrintingOptions = "Opciones de impresión"
PrintDisplayed = "Imprimir elementos mostrados..."
Itemcode = "Código de artículo"
Name = "Nombre del artículo"
Active = "Activo"
ActiveWeb = "Activo en Web"
CategoriesBitmask = "Máscara de categorías"
CreatedOn = "Creado el"
DefaultVatCategory = "Categoría de IVA predeterminada"
Description = "Descripción"
DescriptionPos = "Descripción en POS"
DescriptionsOtherLanguages = "Descripciones en otros idiomas"
DescriptionWeb = "Descripción web"
EnforceAboveCost = "Aplicar por encima del costo"
ExpiryTrackingEnabled = "Seguimiento de caducidad activado"
#Itemcode = "Código de artículo (Nota: antigua notación)"
PermissionsCategory = "Categoría de permisos"
PriceManual = "Precio manual"
VatCategoryAdjustable = "Categoría de IVA ajustable"
VatDependsOnUser = "El IVA depende del usuario"
New = "Nuevo"
Save = "Guardar"
View = "Ver"
Cancel = "Cancelar"
