[en]
Active = "Active"
ActiveWeb = "Active on Web"
CategoriesBitmask = "Categories Bitmask"
CreatedOn = "Created On"
DefaultVatCategory = "Default VAT Category"
Description = "Description"
DescriptionPos = "POS Description"
DescriptionsOtherLanguages = "Descriptions in Other Languages"
DescriptionWeb = "Web Description"
EnforceAboveCost = "Enforce Above Cost"
ExpiryTrackingEnabled = "Expiry Tracking Enabled"
Itemcode = "Item Code"
PermissionsCategory = "Permissions Category"
PriceManual = "Manual Price"
VatCategoryAdjustable = "VAT Category Adjustable"
VatDependsOnUser = "VAT Depends on User"

[si]
"Editor" = "📝 සංස්කාරක"
"BatchEditor" = "📋 බැච් සංස්කාරක"
"Adjustments" = "🔧 වෙනස්කම්"
"Items" = "📦 අයිතම"
"StockOverview" = "📊 කොටස් සමාලෝචනය"
"Locations" = "📍 ස්ථාන"
"Transfers" = "🔄 මාරු"
"Reports" = "📈 වාර්තා"
"Alerts" = "⛑ අනතුරු ඇඟවීම්"
"Search" = "🔍 සෙවුම්"
"MaterialMaster" = "🗃 ද්‍රව්‍ය පාලක"
"GoodsReceipt" = "📥 භාණ්ඩ ලැබීම"
"GoodsIssued" = "📤 භාණ්ඩ නිකුත්කිරීම"
"CycleCount" = "🧮 චක්‍ර ගණන"
"Warehouse" = "🏭 ගබඩා"
"SerialControl" = "🔢 අනුක්‍රමික පාලනය"
"Replenishment" = "🔄 නැවත පිරවීම්"
"BarcodePrint" = "🖨️ බාකෝඩ් මුද්‍රණය"
"Inventory" = "📦 ගබඩා"
"Accounts" = "💰 ගිණුම්"
"HR" = "👥 සේවක කළමනාකරණය"
"CRM" = "🤝 ගනුදෙනු කළමනාකරණය"
"Settings" = "⚙️ සැකසුම්"
"Connection" = "⚙️ සම්බන්ධතාවය"
"About" = "🎫 පිළිබඳ විස්තර"
ReportSelected         = "වාර්තාව තෝරා ඇත"
SearchFor              = "සෙවීමට: "
Results                = "ප්‍රතිඵල: "
CaseInsensitiveF1      = "අකුරු සංවේදනය නොවන [F1]"
CaseSensitiveF2        = "අකුරු සංවේදනය වන [F2]"
ContainsF3             = "අඩංගු [F3]"
StartsWithF4           = "ආරම්භ [F4]"
AnythingAnywhereBRK    = "ඕනෑම දෙයක් ඕනෑම තැන [BRK]"
NormalizeSpellingEND   = "වචන නිවැරදි කිරීම [END]"
SearchIn               = "සොයන්න: "
CaseSensitivitySetting = "අකුරු සංවේදන සැකසුම්"
SearchPosition         = "සෙවුම් ස්ථානය"
Advanced               = "උසස්..."
ExportResults          = "ප්‍රතිඵල ගොනුවට අපනයනය කරන්න..."
ExportEverything       = "සියල්ල ගොනුවට අපනයනය කරන්න..."
ExportDisplayed        = "දර්ශනය කරන ප්‍රතිඵල ගොනුවට අපනයනය කරන්න..."
ExportOptions          = "ගොනුවට අපනයනය විකල්ප"
PrintingOptions        = "මුද්‍රණ විකල්ප"
PrintDisplayed         = "දර්ශනය කරන ප්‍රතිඵල මුද්‍රණය..."
Itemcode = "භාණ්ඩ හැඳුනුම් කේතය"
Name     = "භාණ්ඩ නම"
Active = "සක්‍රීය"
ActiveWeb = "වෙබ් සක්‍රීය"
CategoriesBitmask = "ප්‍රවර්ග බිට්මාස්ක්"
CreatedOn = "නිර්මාණය කරන ලද දිනය"
DefaultVatCategory = "පෙරනිමි VAT ප්‍රවර්ගය"
Description = "විස්තරය"
DescriptionPos = "POS විස්තරය"
DescriptionsOtherLanguages = "වෙනත් භාෂා වල විස්තර"
DescriptionWeb = "වෙබ් විස්තරය"
EnforceAboveCost = "වියදම ඉහළ ක්‍රියාත්මක කිරීම"
ExpiryTrackingEnabled = "කල් ඉකුත් වීම සක්‍රීයයි"
#Itemcode = "අයිතම කේතය"
PermissionsCategory = "අවසර ප්‍රවර්ගය"
PriceManual = "මැනුවල් මිල"
VatCategoryAdjustable = "VAT ප්‍රවර්ගය වෙනස් කළ හැකි"
VatDependsOnUser = "VAT පරිශීලකයා මත රඳා පවතියි"


[ta]
"Editor" = "📝 தொகுப்பாளர்"
"BatchEditor" = "📋 தொகுதி திருத்தி"
"Adjustments" = "🔧 சரிசெய்தல்கள்"
"Items" = "📦 பொருட்கள்"
"StockOverview" = "📊 களஞ்சிய கண்ணோட்டம்"
"Locations" = "📍 இருப்பிடங்கள்"
"Transfers" = "🔄 மாற்றங்கள்"
"Reports" = "📈 அறிக்கைகள்"
"Alerts" = "⛑ எச்சரிக்கை"
"Search" = "🔍 தேடல்"
"MaterialMaster" = "🗃 பொருள் மேலாளர்"
"GoodsReceipt" = "📥 பொருட்கள் பெறுதல்"
"GoodsIssued" = "📤 பொருட்கள் வெளியீடு"
"CycleCount" = "🧮 சுழற்சி எண்ணிக்கை"
"Warehouse" = "🏭 களஞ்சியம்"
"SerialControl" = "🔢 தொடர் கட்டுப்பாடு"
"Replenishment" = "🔄 நிரப்புதல்"
"BarcodePrint" = "🖨️ பார்கோடு அச்சிடுதல்"
"Inventory" = "📦 களஞ்சியம்"
"Accounts" = "💰 கணக்குகள்"
"HR" = "👥 மனிதவள மேலாண்மை"
"CRM" = "🤝 வாடிக்கையாளர் மேலாண்மை"
"Settings" = "⚙️ அமைப்புகள்"
"Connection" = "⚙️ தற்போதைய இணைப்பு"
"About" = "🎫 பற்றி"
ReportSelected         = "அறிக்கை தெரிவு செய்யப்பட்டு உள்ளது"
SearchFor              = "தேடவும்: "
Results                = "முடிவுகள்: "
CaseInsensitiveF1      = "எழுத்துப் பொருத்தமற்றது [F1]"
CaseSensitiveF2        = "எழுத்துப் பொருத்தமானது [F2]"
ContainsF3             = "உள்ளடக்கம் [F3]"
StartsWithF4           = "ஆரம்பம் [F4]"
AnythingAnywhereBRK    = "எதையும் எங்கும் [BRK]"
NormalizeSpellingEND   = "எழுத்து ஒழுங்குபடுத்தல் [END]"
SearchIn               = "தேடல் இடம்: "
CaseSensitivitySetting = "எழுத்து உணர்திறன் அமைப்பு"
SearchPosition         = "தேடல் நிலை"
Advanced               = "மேம்பட்டது..."
ExportResults          = "முடிவுகளை கோப்பாக ஏற்றுமதி செய்க..."
ExportEverything       = "எல்லாவற்றையும் கோப்பாக ஏற்றுமதி செய்க..."
ExportDisplayed        = "காண்பிக்கப்படும் முடிவுகளை கோப்பாக ஏற்றுமதி செய்க..."
ExportOptions          = "கோப்பு ஏற்றுமதி விருப்பங்கள்"
PrintingOptions        = "அச்சிடும் விருப்பங்கள்"
PrintDisplayed         = "காண்பிக்கப்படும் முடிவுகளை அச்சிடுக..."
Itemcode = "பொருள் குறியீடு"
Name     = "பெயர்"
Active = "செயலில்"
ActiveWeb = "இணையத்தில் செயலில்"
CategoriesBitmask = "வகை பிட்மாஸ்க்"
CreatedOn = "உருவாக்கப்பட்ட தேதி"
DefaultVatCategory = "இயல்புநிலை வரி வகை"
Description = "விவரம்"
DescriptionPos = "POS விவரம்"
DescriptionsOtherLanguages = "மற்ற மொழிகளில் விவரம்"
DescriptionWeb = "இணைய விவரம்"
EnforceAboveCost = "செலவிற்கு மேல் கட்டாயப்படுத்தல்"
ExpiryTrackingEnabled = "காலாவதி கண்காணிப்பு இயக்கு"
#Itemcode = "உருப்படி குறியீடு"
PermissionsCategory = "அனுமதி வகை"
PriceManual = "கைமுறை விலை"
VatCategoryAdjustable = "வரி வகை மாற்றக்கூடியது"
VatDependsOnUser = "வரி பயனரை சார்ந்தது"


[hi]
"Editor" = "📝 संपादक"
"BatchEditor" = "📋 बैच संपादक"
"Adjustments" = "🔧 समायोजन"
"Items" = "📦 वस्तुएँ"
"StockOverview" = "📊 स्टॉक अवलोकन"
"Locations" = "📍 स्थान"
"Transfers" = "🔄 स्थानांतरण"
"Reports" = "📈 रिपोर्ट"
"Alerts" = "⛑ चेतावनी"
"Search" = "🔍 खोज"
"MaterialMaster" = "🗃 सामग्री प्रबंधक"
"GoodsReceipt" = "📥 माल प्राप्ति"
"GoodsIssued" = "📤 माल जारी"
"CycleCount" = "🧮 चक्र गिनती"
"Warehouse" = "🏭 गोदाम"
"SerialControl" = "🔢 क्रम नियंत्रण"
"Replenishment" = "🔄 पुनःपूर्ति"
"BarcodePrint" = "🖨️ बारकोड प्रिंट"
"Inventory" = "📦 इन्वेंटरी"
"Accounts" = "💰 खाते"
"HR" = "👥 मानव संसाधन"
"CRM" = "🤝 ग्राहक प्रबंधन"
"Settings" = "⚙️ सेटिंग्स"
"Connection" = "⚙️ वर्तमान कनेक्शन"
"About" = "🎫 बारे में"
ReportSelected         = "रिपोर्ट चुनी गई"
SearchFor              = "खोजें: "
Results                = "परिणाम: "
CaseInsensitiveF1      = "केस-संवेदनहीन [F1]"
CaseSensitiveF2        = "केस-संवेदनशील [F2]"
ContainsF3             = "शामिल [F3]"
StartsWithF4           = "से शुरू [F4]"
AnythingAnywhereBRK    = "कुछ भी कहीं भी [BRK]"
NormalizeSpellingEND   = "वर्तनी सामान्य करें [END]"
SearchIn               = "में खोजें: "
CaseSensitivitySetting = "अक्षर संवेदनशीलता सेटिंग"
SearchPosition         = "खोज स्थिति"
Advanced               = "उन्नत..."
ExportResults          = "परिणामों को फ़ाइल में निर्यात करें..."
ExportEverything       = "सभी को फ़ाइल में निर्यात करें..."
ExportDisplayed        = "दिखाए गए परिणामों को फ़ाइल में निर्यात करें..."
ExportOptions          = "फ़ाइल निर्यात विकल्प"
PrintingOptions        = "प्रिंट विकल्प"
PrintDisplayed         = "दिखाए गए परिणाम प्रिंट करें..."
Itemcode = "आइटम कोड"
Name     = "आइटम नाम"
Active = "सक्रिय"
ActiveWeb = "वेब पर सक्रिय"
CategoriesBitmask = "श्रेणी बिटमास्क"
CreatedOn = "निर्मित तिथि"
DefaultVatCategory = "डिफ़ॉल्ट वैट श्रेणी"
Description = "विवरण"
DescriptionPos = "POS विवरण"
DescriptionsOtherLanguages = "अन्य भाषाओं में विवरण"
DescriptionWeb = "वेब विवरण"
EnforceAboveCost = "लागत से ऊपर लागू करें"
ExpiryTrackingEnabled = "समाप्ति ट्रैकिंग सक्षम"
#Itemcode = "आइटम कोड"
PermissionsCategory = "अनुमति श्रेणी"
PriceManual = "मैनुअल मूल्य"
VatCategoryAdjustable = "वैट श्रेणी समायोज्य"
VatDependsOnUser = "वैट उपयोगकर्ता पर निर्भर"

[fr]
"Editor" = "📝 Éditeur"
"BatchEditor" = "📋 Éditeur par lots"
"Adjustments" = "🔧 Ajustements"
"Items" = "📦 Articles"
"StockOverview" = "📊 Aperçu du stock"
"Locations" = "📍 Emplacements"
"Transfers" = "🔄 Transferts"
"Reports" = "📈 Rapports"
"Alerts" = "⛑ Alertes"
"Search" = "🔍 Recherche"
"MaterialMaster" = "🗃 Gestion des matériaux"
"GoodsReceipt" = "📥 Réception des marchandises"
"GoodsIssued" = "📤 Sortie des marchandises"
"CycleCount" = "🧮 Comptage cyclique"
"Warehouse" = "🏭 Entrepôt"
"SerialControl" = "🔢 Contrôle de série"
"Replenishment" = "🔄 Réapprovisionnement"
"BarcodePrint" = "🖨️ Impression de codes-barres"
"Inventory" = "📦 Inventaire"
"Accounts" = "💰 Comptes"
"HR" = "👥 Ressources Humaines"
"CRM" = "🤝 Gestion de la relation client"
"Settings" = "⚙️ Paramètres"
"Connection" = "⚙️ Connexion actuelle"
"About" = "🎫 À propos"
ReportSelected         = "Rapport sélectionné"
SearchFor              = "Rechercher : "
Results                = "Résultats : "
CaseInsensitiveF1      = "Insensible à la casse [F1]"
CaseSensitiveF2        = "Sensible à la casse [F2]"
ContainsF3             = "Contient [F3]"
StartsWithF4           = "Commence par [F4]"
AnythingAnywhereBRK    = "N'importe quoi n'importe où [BRK]"
NormalizeSpellingEND   = "Normaliser l'orthographe [END]"
SearchIn               = "Rechercher dans : "
CaseSensitivitySetting = "Sensibilité à la casse"
SearchPosition         = "Position de recherche"
Advanced               = "Avancé..."
ExportResults          = "Exporter les résultats vers un fichier..."
ExportEverything       = "Exporter tout vers un fichier..."
ExportDisplayed        = "Exporter les affichages vers un fichier..."
ExportOptions          = "Options d'exportation de fichier"
PrintingOptions        = "Options d'impression"
PrintDisplayed         = "Imprimer les affichages..."
Itemcode = "Code article"
Name     = "Nom de l'article"
Active = "Actif"
ActiveWeb = "Actif sur le Web"
CategoriesBitmask = "Masque de catégories"
CreatedOn = "Créé le"
DefaultVatCategory = "Catégorie de TVA par défaut"
Description = "Description"
DescriptionPos = "Description POS"
DescriptionsOtherLanguages = "Descriptions dans d’autres langues"
DescriptionWeb = "Description Web"
EnforceAboveCost = "Appliquer au‐dessus du coût"
ExpiryTrackingEnabled = "Suivi de péremption activé"
#Itemcode = "Code d’article"
PermissionsCategory = "Catégorie de permissions"
PriceManual = "Prix manuel"
VatCategoryAdjustable = "Catégorie de TVA ajustable"
VatDependsOnUser = "TVA dépend de l’utilisateur"