using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Eto.Forms;

namespace CommonUi
{
    public static class PanelGenerators
    {
        public static Dictionary<
            string,
            Func<string[], TextBox?, ILookupSupportedChildPanel>
        > Defaults()
        {
            return new Dictionary<string, Func<string[], TextBox?, ILookupSupportedChildPanel>>()
            {
                {
                    "DiscountPanel",
                    (string[] mappings, TextBox? parentTextBox) =>
                    {
                        // Assume DiscountMarkupPanel is implemented elsewhere (generated by EF Core)
                        // and follows the mapping order: mappings[0]=Absolute, mappings[1]=Percentage.
                        Console.WriteLine($"DiscountPanel mapping: {mappings[0]}, {mappings[1]}");
                        return new DiscountMarkupPanel(
                            parentTextBox ?? throw new ArgumentNullException(nameof(parentTextBox)),
                            "Discount",
                            Orientation.Vertical,
                            Mappings: mappings
                        );
                    }
                },
                {
                    "DatePickerPanel",
                    (string[] mappings, TextBox? _) => new DatePickerPanel(mappings: mappings)
                },
                {
                    "VatCategoryLookupPanel",
                    (string[] mappings, TextBox? _) => new VatCategoryLookupPanel(mappings: mappings)
                },
                {
                    "PhoneNumberLookupPanel",
                    (string[] mappings, TextBox? _) => new PhoneNumberLookupPanel(mappings: mappings)
                }
            };
        }
    }
}
