<Project Sdk="Microsoft.NET.Sdk">
	<Import Project="Sdk.props" Sdk="Microsoft.NET.Sdk.Razor" />
    <PropertyGroup>
		<Features>runtime-async=on</Features>
        <OutputType>Exe</OutputType>
        <TargetFramework>net11.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
		<LangVersion>preview</LangVersion>
        <!--<PublishAot>true</PublishAot>-->
        <!--<PublishTrimmed>true</PublishTrimmed>-->
        <!--<PublishSingleFile>true</PublishSingleFile>-->
        <InvariantGlobalization>true</InvariantGlobalization>
        <RuntimeIdentifier>win-x64</RuntimeIdentifier>
        <ApplicationIcon>log_2.ico</ApplicationIcon>
        <Platforms>AnyCPU;x64</Platforms>
        <Description>Health Monitor (Built: $([System.DateTime]::Now.ToString("o")))</Description>
        <Copyright>Rishikeshan Sulochana/Lavakumar, OSLv3</Copyright>
        <Version>0.1.0</Version>
        <PublisherName>Rishikeshan S/L</PublisherName>
        <ProductVersion>0.1.0 $([System.DateTime]::Now.ToString("o"))</ProductVersion>
        <WebPage>https://rishikeshan.com</WebPage>
        <PackageLicenseExpression>OSL-3.0</PackageLicenseExpression>
        <Optimize>true</Optimize>
        <Title>Health Monitor</Title>
		<AddRazorSupportForMvc>true</AddRazorSupportForMvc>
		<RazorCompileOnBuild>true</RazorCompileOnBuild>
		<RazorCompileOnPublish>true</RazorCompileOnPublish>
		<EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
		<IncludeRazorContent>true</IncludeRazorContent>
		<MvcRazorCompileOnPublish>true</MvcRazorCompileOnPublish>
		<DebugType>embedded</DebugType>
		<EnableUnsafeBinaryFormatterSerialization>false</EnableUnsafeBinaryFormatterSerialization>
		<EventSourceSupport>false</EventSourceSupport>
		<HttpActivityPropagationSupport>false</HttpActivityPropagationSupport>
		<InvariantGlobalization>true</InvariantGlobalization>
		<MetadataUpdaterSupport>false</MetadataUpdaterSupport>
		<MetricsSupport>false</MetricsSupport>
		<EnableUnsafeUTF7Encoding>false</EnableUnsafeUTF7Encoding>
		<UseSizeOptimizedLinq>true</UseSizeOptimizedLinq>
    </PropertyGroup>
    <ItemGroup>
        <Content Include="log_2.ico" />
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation" Version="10.0.5" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.5">
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
            <PrivateAssets>all</PrivateAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.5" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.5" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.5" />
        <PackageReference Include="SQLitePCLRaw.provider.dynamic_cdecl" Version="3.0.2" />
        <PackageReference Include="SQLitePCLRaw.provider.e_sqlite3" Version="3.0.2" />
        <PackageReference Include="SQLitePCLRaw.provider.sqlite3" Version="3.0.2" />
        <PackageReference Include="Tomlyn" Version="2.3.0" />
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
		<!--
		<FrameworkReference Include="Microsoft.NET.Sdk.Web" />
		<FrameworkReference Include="Microsoft.NET.Sdk.Razor" />
		-->
		<PackageReference Include="RazorSlices" Version="0.10.0" />
		
		
	</ItemGroup>
    <ItemGroup>
		<Content Include="HealthMonitor.toml">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </Content>
		<Content Include="logs.sqlite3">
            <CopyToOutputDirectory>Never</CopyToOutputDirectory>
        </Content>
		<Content Include="logs.sqlite3.rvhealthmonitorlogfile">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
        <Content Include="new.logs.sqlite3.rvhealthmonitorlogfile">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </Content>
		<!-- 1. Compile .cshtml files AND copy them to output -->
		<Content Update="Pages\**\*.cshtml">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		

		<!-- 2. Explicitly copy static assets (js/css) from Pages/static -->
		<Content Include="Pages\static\**">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
    </ItemGroup>
	<ItemGroup>
		<EmbeddedResource Include="Pages\**\*.cshtml" />
	</ItemGroup>
	<PropertyGroup>
		<GarbageCollectionAdaptationMode>1</GarbageCollectionAdaptationMode>
	</PropertyGroup>

   <!--<ItemGroup>
      <Folder Include="Pages\Pages\" />
    </ItemGroup>-->
	<Import Project="Sdk.targets" Sdk="Microsoft.NET.Sdk.Razor" />
</Project>
