destinations = ["192.168.1.1", "8.8.8.8", "1.1.1.1"]
RetentionDays = 15
LogFile = "logs.sqlite3.rvhealthmonitorlogfile"
SleepTimeMsBetweenPointsProc = 60000
SleepTimeMsBetweenPointsPing = 15000
AutoVacuum = true
AutoVacuumOnStartup = true