destinations = ["192.168.1.1", "8.8.8.8", "1.1.1.1"]
RetentionDays = 15 # Should be a sensible default
LogFile = "logs.sqlite3.rvhealthmonitorlogfile"
SleepTimeMsBetweenPointsProc = 900000 # 15 minutes
SleepTimeMsBetweenPointsPing = 30000 # Half a minute
AutoVacuum = true
AutoVacuumOnStartup = true
Title = "Health Monitor (logging service), © Rishikeshan S/L, License: Open Software License, V3 (no later)."