<Project Sdk="Microsoft.NET.Sdk">
	<Import Project="Sdk.props" Sdk="Microsoft.NET.Sdk.Razor" />
    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <!--<PublishAot>true</PublishAot>-->
        <!--<PublishTrimmed>true</PublishTrimmed>-->
        <PublishSingleFile>true</PublishSingleFile>
        <InvariantGlobalization>true</InvariantGlobalization>
        <RuntimeIdentifier>win-x64</RuntimeIdentifier>
        <ApplicationIcon>log_2.ico</ApplicationIcon>
        <Platforms>AnyCPU;x64</Platforms>
        <Description>Health Monitor (Built: $([System.DateTime]::Now.ToString("o")))</Description>
        <Copyright>Rishikeshan Sulochana/Lavakumar, OSLv3</Copyright>
        <Version>0.1.0</Version>
        <PublisherName>Rishikeshan S/L</PublisherName>
        <ProductVersion>0.1.0 $([System.DateTime]::Now.ToString("o"))</ProductVersion>
        <WebPage>https://rishikeshan.com</WebPage>
        <PackageLicenseExpression>OSL-3.0</PackageLicenseExpression>
        <Optimize>true</Optimize>
        <Title>Health Monitor</Title>
		<AddRazorSupportForMvc>true</AddRazorSupportForMvc>
		<RazorCompileOnBuild>true</RazorCompileOnBuild>
		<RazorCompileOnPublish>true</RazorCompileOnPublish>
		<UseRazorSourceGenerator>true</UseRazorSourceGenerator>
		
    </PropertyGroup>
    <ItemGroup>
        <Content Include="log_2.ico" />
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="8.0.25" />
        <PackageReference Include="Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation" Version="8.0.25" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.7">
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
            <PrivateAssets>all</PrivateAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="8.0.7" />
        <PackageReference Include="Tomlyn" Version="0.17.0" />
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
		<!--
		<FrameworkReference Include="Microsoft.NET.Sdk.Web" />
		<FrameworkReference Include="Microsoft.NET.Sdk.Razor" />
		-->
		<PackageReference Include="RazorSlices" Version="0.9.5" />
		
		
	</ItemGroup>
    <ItemGroup>
        <None Update="HealthMonitor.toml">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Update="logs.sqlite3">
            <CopyToOutputDirectory>Never</CopyToOutputDirectory>
        </None>
        <None Update="logs.sqlite3.rvhealthmonitorlogfile">
            <CopyToOutputDirectory>Never</CopyToOutputDirectory>
        </None>
        <None Update="new.logs.sqlite3.rvhealthmonitorlogfile">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
		<!-- 1. Compile .cshtml files AND copy them to output -->
		<Content Update="Pages\**\*.cshtml">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>

		<!-- 2. Explicitly copy static assets (js/css) from Pages/static -->
		<Content Include="Pages\static\**">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
    </ItemGroup>
   <!--<ItemGroup>
      <Folder Include="Pages\Pages\" />
    </ItemGroup>-->
	<Import Project="Sdk.targets" Sdk="Microsoft.NET.Sdk.Razor" />
</Project>
