INSERT INTO
	PUBLIC.CATALOGUE (
		ITEMCODE,
		DESCRIPTION,
		ACTIVE,
		CREATED_ON,
		DESCRIPTION_POS,
		DESCRIPTION_WEB,
		DESCRIPTIONS_OTHER_LANGUAGES,
		DEFAULT_VAT_CATEGORY,
		VAT_DEPENDS_ON_USER,
		VAT_CATEGORY_ADJUSTABLE,
		PRICE_MANUAL,
		ENFORCE_ABOVE_COST,
		ACTIVE_WEB
	)
SELECT itemcode, "desc", true, now(), "desc", "desc", NULL, 1, false, true, true, true, true FROM imported_dummy.sih;