INSERT INTO
	PUBLIC.INVENTORY (
		ITEMCODE,
		BATCHCODE,
		BATCH_ENABLED,
		MFG_DATE,
		EXP_DATE,
		PACKED_SIZE,
		UNITS,
		MEASUREMENT_UNIT,
		MARKED_PRICE,
		SELLING_PRICE,
		COST_PRICE,
		VOLUME_DISCOUNTS,
		SUPPLIERCODE,
		USER_DISCOUNTS
	)

SELECT
	ITEMCODE+200000,
	1,
	TRUE,
	NOW(),
	NOW() + CAST(
		(
			(CAST(ROUND(730.0 * RANDOM())::INT % 730 AS TEXT)) || ' DAYS'
		) AS INTERVAL
	),
	1 + FLOOR(12 * RANDOM())::INT,
	1 + FLOOR(12 * RANDOM())::INT,
	'grams',
	sell*1.5,
	sell,
	cost,
	true,
	1 + FLOOR(12 * RANDOM())::INT,
	true
FROM imported_dummy.sih;