#padding = [160, 80, 80]

[ReceiptPrinter]
PageHeight = 700.0
PageWidth = 400.0
FontSize = 10.0
LineHeight = 20.0
FontFamily = "Monospace"

[ReceiptPrinter.images]
# Top images to be rendered in the header section.
top = [
  { Path = "logo.png", XPosition = "left", YPosition = "top", Width = 100, Height = 50 },
  { Path = "banner.png", XPosition = "center", YPosition = "top", Width = 200, Height = 100 }
]

# Bottom images to be rendered in the footer section.
bottom = [
  { Path = "footer.png", XPosition = "left", YPosition = "bottom", Width = 150, Height = 50 },
  { Path = "stamp.png", XPosition = "bottom", YPosition = "bottom", Width = 100, Height = 100 }
]

[default.name]
background_color = "#FFFF00"
foreground_color = "#000000"
background_color_changed = "#FF0000"
foreground_color_changed = "#FFFFFF"
font_family = "Arial"
font_size = "16"
font_style = "Regular"
control_size = "100,40"

[default.new]
background_color = "#ccc"
foreground_color = "#000000"
background_color_changed = "#FF0000"
foreground_color_changed = "#FFFFFF"
font_family = "Arial"
font_size = "16"
font_style = "Regular"
control_size = "100,40"

[default.save]
background_color = "#FF00FF"
foreground_color = "#000000"
background_color_changed = "#FF0000"
foreground_color_changed = "#FFFFFF"
font_family = "Arial"
font_size = "16"
font_style = "Regular"
control_size = "100,40"

[default.cancel]
background_color = "#FF0000"
foreground_color = "#000000"
background_color_changed = "#FF0000"
foreground_color_changed = "#FFFFFF"
font_family = "Arial"
font_size = "16"
font_style = "Regular"
control_size = "100,40"

[default.view]
background_color = "#FFFFFF"
foreground_color = "#000000"
background_color_changed = "#FF0000"
foreground_color_changed = "#FFFFFF"
font_family = "Arial"
font_size = "16"
font_style = "Regular"
control_size = "100,40"

[default.form]
#background_color = "#000000"
#foreground_color = "#FFFFFF"
background_color_changed = "#FFFFFF"
foreground_color_changed = "#FF0000"
font_family = "Arial"
font_size = "16"
font_style = "Regular"
control_size = "10,40"

[default.localName]
background_color = "#FF0000"
foreground_color = "#0000FF"
background_color_changed = "#FF00FF"
foreground_color_changed = "#FFFFFF"
font_family = "Arial"
font_size = "12"
font_style = "Regular"
control_size = "100,40"

[default.location]
background_color = "#FF00FF"
foreground_color = "#00FF00"
background_color_changed = "#FF0000"
foreground_color_changed = "#FFFFFF"
font_family = "Arial"
font_size = "24"
font_style = "Regular"
control_size = "100,40"

[default.Legend]
background_color = "#FF00FF"
foreground_color = "#00FF00"
background_color_changed = "#FF0000"
foreground_color_changed = "#00FFFF"
font_family = "Arial"
font_size = "24"
font_style = "Regular"
control_size = "100,40"

[default.float]
background_color = "#FF00FF"
foreground_color = "#00FF00"
background_color_changed = "#FF0000"
foreground_color_changed = "#FFFFFF"
font_family = "Arial"
font_size = "24"
font_style = "Regular"
control_size = "100,40"

[default.bool]
background_color = "#FF00FF"
foreground_color = "#00FF00"
background_color_changed = "#FF0000"
foreground_color_changed = "#FFFFFF"
font_family = "Arial"
font_size = "24"
font_style = "Regular"
control_size = "100,40"


#[ReceiptPrinter]
ReceiptPrinter.PageHeight = 600.0
ReceiptPrinter.PageWidth = 200.0
ReceiptPrinter.FontSize = 20.0
ReceiptPrinter.LineHeight = 20.0
ReceiptPrinter.FontFamily = "IBM COURIER"